// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace SnomedData.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SnomedConcreteValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("CharacteristicTypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConcreteValueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EffectiveTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModifierId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModuleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RelationshipGroup")
                        .HasColumnType("integer");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SnomedConcreteValues");
                });

            modelBuilder.Entity("SnomedData.Models.LoincRecord", b =>
                {
                    b.Property<string>("LOINC_NUM")
                        .HasColumnType("text");

                    b.Property<string>("AskAtOrderEntry")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AssociatedObservations")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CHANGE_REASON_PUBLIC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CHNG_TYPE")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CLASS")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CLASSTYPE")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("COMMON_ORDER_RANK")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("COMMON_TEST_RANK")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("COMPONENT")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CONSUMER_NAME")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DefinitionDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EXAMPLE_UCUM_UNITS")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EXAMPLE_UNITS")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EXMPL_ANSWERS")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EXTERNAL_COPYRIGHT_LINK")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EXTERNAL_COPYRIGHT_NOTICE")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FORMULA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HL7_ATTACHMENT_STRUCTURE")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HL7_FIELD_SUBFIELD_ID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LONG_COMMON_NAME")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("METHOD_TYP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ORDER_OBS")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PROPERTY")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PanelType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RELATEDNAMES2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SCALE_TYP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SHORTNAME")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("STATUS")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("STATUS_REASON")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("STATUS_TEXT")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SURVEY_QUEST_SRC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SURVEY_QUEST_TEXT")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SYSTEM")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TIME_ASPCT")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UNITSREQUIRED")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ValidHL7AttachmentRequest")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VersionFirstReleased")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VersionLastChanged")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LOINC_NUM");

                    b.ToTable("LoincRecords");
                });

            modelBuilder.Entity("SnomedData.Models.SnomedConcept", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("ConceptId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DefinitionStatusId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EffectiveTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModuleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SnomedConcepts");
                });

            modelBuilder.Entity("SnomedData.Models.SnomedDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("CaseSignificanceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConceptId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EffectiveTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModuleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SnomedDescriptions");
                });

            modelBuilder.Entity("SnomedData.Models.SnomedTextDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("CaseSignificanceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConceptId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EffectiveTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModuleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SnomedTextDefinitionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TextDefinition");
                });

            modelBuilder.Entity("SnomedData.Models.StatedRelationship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("CharacteristicTypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DestinationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EffectiveTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModifierId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModuleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RelationshipGroup")
                        .HasColumnType("integer");

                    b.Property<string>("RelationshipId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StatedRelationships");
                });

            modelBuilder.Entity("SnomedOwlExpression", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("EffectiveTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModuleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwlExpression")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwlId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReferencedComponentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefsetId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SnomedOwlExpressions");
                });

            modelBuilder.Entity("SnomedRelationship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("CharacteristicTypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DestinationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EffectiveTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModifierId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModuleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RelationshipGroup")
                        .HasColumnType("integer");

                    b.Property<string>("RelationshipId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SnomedRelationships");
                });
#pragma warning restore 612, 618
        }
    }
}
